config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root    'static_pages#home'
  get     '/help',      to: 'static_pages#help'
  get     '/about',     to: 'static_pages#about'
  get     '/contact',   to: 'static_pages#contact'
  get     '/signup',    to: 'users#new'
  post    '/signup',    to: 'users#create' # exercise 7.3.4.2
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token

  # validates :name, presence: true, length: {maximum: 50}
  # validates :email, presence: true, length: {maximum: 255}

  # before_save {self.email = email.downcase }
  # before_save { email.downcase!}  # equivalent to the above commented statement
  before_save :downcase_email       # method reference preferred over a passed block (ch11)

  before_create :create_activation_digest

  validates(:name, {presence: true,
                     length: {maximum: 50}}
  )
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates(:email, {presence: true,
                     length: {maximum: 255},
                     format: {with: VALID_EMAIL_REGEX},
                     uniqueness: {case_sensitive: false},
  })
  has_secure_password
  validates(:password, {presence: true, length: {minimum: 6}, allow_nil: true })

  # returns hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # returns a random new token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # remember a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")

    if digest  # only attempt to authenticate if a digest exists
      BCrypt::Password.new(digest).is_password?(token)
    else
      return false
    end

    # original:
    # authenticated?(remember_token)
    # ...
    # if remember_token BCrypt:... else return false
  end

  # forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # activates an account
  def activate
    # redundant after ex 11.3.3.1
    # update_attribute(:activated,  true)
    # update_attribute(:activated_at, Time.zone.now)

    # exercise 11.3.3.1
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # sends activation account
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # private section
  private

    # converts email to lowercase
    def downcase_email
      email.downcase!
    end

    # creates and assigns the activation token and digest
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(self.activation_token)
    end
  # end private
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,    only: [:index, :edit, :update, :destroy]
  before_action :correct_user,      only: [:edit, :update]
  before_action :admin_user,        only: :destroy


  def index
    # @users = User.all
    # @users = User.paginate(page: params[:page])

    # exercise 11.3.3.2
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def new
    # debugger
    # value of @user in /users/new is nil (exercise 7.1.3)
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # handle a successful save
      # ch11
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url

      # old code for when user gets immediate access to account w/o email
      # log_in(@user)
      # flash[:success] = "Welcome to Sample App!"
      # redirect_to @user # also works: redirect_to user_url(@user); rails understands the former [magic]
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    # debugger
    redirect_to root_url and return unless @user.activated?
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # handle a successful update
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  # private section: start
  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # before filters

    # confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  # private section: end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.


  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    # size = options[:size]

    # 2017.02.16, ex 7.4.4.1 - this if block has error
    # ActionView::Template::Error: nil is not a valid asset source app/helpers/users_helper.rb:21:in `gravatar_for'

    # getting images to display on development versus production
    # http://stackoverflow.com/questions/38222989/gravatar-image-not-displaying
    # if Rails.env.production?
    #    puts "console: i'm in production!"
    #    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    # elsif Rails.env.development?
    #   # still doesn't work ?_?
    #   puts "console: i'm in development!"
    #   gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    # end

    # error is on ghostery - it blocks gravatar's redirects
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:form_path)) do |f| %>
    <%= render 'shared/error_messages', object: @user %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user)%>
      | <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "You sure?" }%>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<% provide(:form_path, user_path) %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form'%>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%# @users.each do |user| %>
      <%# li>
        <%#= gravatar_for user, size: 50 %>
        <%#= link_to user.name, user %>
      <%# /li> %>
      <%#=	 render user %>
  <%# end %>
  <%# more clever way even below: %>
  <%= render @users %>

</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%# <% provide(:title, 'Sign up') %>
<%# <h1>Sign up</h1>  %>
<%# <p>This will be a signup page for new users.</p>  %>

<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% provide(:form_path, signup_path) %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form'%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>